/*
Nudm_SDM

Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 2.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ClockQualityDetailLevel Indicates the Clock Quality Detail Level.
type ClockQualityDetailLevel struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ClockQualityDetailLevel) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ClockQualityDetailLevel)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ClockQualityDetailLevel) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableClockQualityDetailLevel struct {
	value *ClockQualityDetailLevel
	isSet bool
}

func (v NullableClockQualityDetailLevel) Get() *ClockQualityDetailLevel {
	return v.value
}

func (v *NullableClockQualityDetailLevel) Set(val *ClockQualityDetailLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableClockQualityDetailLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableClockQualityDetailLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClockQualityDetailLevel(val *ClockQualityDetailLevel) *NullableClockQualityDetailLevel {
	return &NullableClockQualityDetailLevel{value: val, isSet: true}
}

func (v NullableClockQualityDetailLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClockQualityDetailLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


