/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A2XSubscriptionDataRetrievalAPIController binds http requests to an api service and writes the service results to the http response
type A2XSubscriptionDataRetrievalAPIController struct {
	service      A2XSubscriptionDataRetrievalAPIServicer
	errorHandler ErrorHandler
}

// A2XSubscriptionDataRetrievalAPIOption for how the controller is set up.
type A2XSubscriptionDataRetrievalAPIOption func(*A2XSubscriptionDataRetrievalAPIController)

// WithA2XSubscriptionDataRetrievalAPIErrorHandler inject ErrorHandler into controller
func WithA2XSubscriptionDataRetrievalAPIErrorHandler(h ErrorHandler) A2XSubscriptionDataRetrievalAPIOption {
	return func(c *A2XSubscriptionDataRetrievalAPIController) {
		c.errorHandler = h
	}
}

// NewA2XSubscriptionDataRetrievalAPIController creates a default api controller
func NewA2XSubscriptionDataRetrievalAPIController(s A2XSubscriptionDataRetrievalAPIServicer, opts ...A2XSubscriptionDataRetrievalAPIOption) Router {
	controller := &A2XSubscriptionDataRetrievalAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the A2XSubscriptionDataRetrievalAPIController
func (c *A2XSubscriptionDataRetrievalAPIController) Routes() Routes {
	return Routes{
		"GetA2xData": Route{
			strings.ToUpper("Get"),
			"/nudm-sdm/v2/{supi}/a2x-data",
			c.GetA2xData,
		},
	}
}

// GetA2xData - retrieve a UE's A2X Subscription Data
func (c *A2XSubscriptionDataRetrievalAPIController) GetA2xData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	supiParam := params["supi"]
	if supiParam == "" {
		c.errorHandler(w, r, &RequiredError{"supi"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetA2xData(r.Context(), supiParam, supportedFeaturesParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
