/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController binds http requests to an api service and writes the service results to the http response
type RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController struct {
	service      RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIServicer
	errorHandler ErrorHandler
}

// RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIOption for how the controller is set up.
type RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIOption func(*RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController)

// WithRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIErrorHandler inject ErrorHandler into controller
func WithRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIErrorHandler(h ErrorHandler) RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIOption {
	return func(c *RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController) {
		c.errorHandler = h
	}
}

// NewRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController creates a default api controller
func NewRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController(s RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIServicer, opts ...RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIOption) Router {
	controller := &RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController
func (c *RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController) Routes() Routes {
	return Routes{
		"GetRangingSlPosData": Route{
			strings.ToUpper("Get"),
			"/nudm-sdm/v2/{supi}/ranging-slpos-data",
			c.GetRangingSlPosData,
		},
	}
}

// GetRangingSlPosData - retrieve a UE's Ranging and Sidelink Positioning Subscription Data
func (c *RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController) GetRangingSlPosData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	supiParam := params["supi"]
	if supiParam == "" {
		c.errorHandler(w, r, &RequiredError{"supi"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetRangingSlPosData(r.Context(), supiParam, supportedFeaturesParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
