/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// LocationPrivacyInd - Indicates one of the mutually exclusive global settings (if the location is allowed or disallowed). 
type LocationPrivacyInd struct {
}

// AssertLocationPrivacyIndRequired checks if the required fields are not zero-ed
func AssertLocationPrivacyIndRequired(obj LocationPrivacyInd) error {
	return nil
}

// AssertLocationPrivacyIndConstraints checks if the values respects the defined constraints
func AssertLocationPrivacyIndConstraints(obj LocationPrivacyInd) error {
	return nil
}
