/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AfRequestAuthorization - AF Request Authorization
type AfRequestAuthorization struct {

	GptpAllowedInfo GptpAllowedInfo `json:"gptpAllowedInfo,omitempty"`

	AstiAllowedInfo AstiAllowedInfo `json:"astiAllowedInfo,omitempty"`
}

// AssertAfRequestAuthorizationRequired checks if the required fields are not zero-ed
func AssertAfRequestAuthorizationRequired(obj AfRequestAuthorization) error {
	if err := AssertGptpAllowedInfoRequired(obj.GptpAllowedInfo); err != nil {
		return err
	}
	if err := AssertAstiAllowedInfoRequired(obj.AstiAllowedInfo); err != nil {
		return err
	}
	return nil
}

// AssertAfRequestAuthorizationConstraints checks if the values respects the defined constraints
func AssertAfRequestAuthorizationConstraints(obj AfRequestAuthorization) error {
	return nil
}
