/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// SharedDataTreatmentInstruction - Indicates the presence of this attribute in the individual data. Otherwise, the individual data takes precedence, by default. 
type SharedDataTreatmentInstruction struct {
}

// AssertSharedDataTreatmentInstructionRequired checks if the required fields are not zero-ed
func AssertSharedDataTreatmentInstructionRequired(obj SharedDataTreatmentInstruction) error {
	return nil
}

// AssertSharedDataTreatmentInstructionConstraints checks if the values respects the defined constraints
func AssertSharedDataTreatmentInstructionConstraints(obj SharedDataTreatmentInstruction) error {
	return nil
}
