/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AreaUsageInd - Indicates one of the mutually exclusive global settings (whether the UE is allowed to generate and send the reports inside or outside the event report expected area). 
type AreaUsageInd struct {
}

// AssertAreaUsageIndRequired checks if the required fields are not zero-ed
func AssertAreaUsageIndRequired(obj AreaUsageInd) error {
	return nil
}

// AssertAreaUsageIndConstraints checks if the values respects the defined constraints
func AssertAreaUsageIndConstraints(obj AreaUsageInd) error {
	return nil
}
