/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// QmcAreaScope - This IE contains the area in Cells or Tracking Areas where the QMC data collection shall take place. 
type QmcAreaScope struct {

	NrCellIdList []string `json:"nrCellIdList,omitempty"`

	TacList []string `json:"tacList,omitempty"`

	TaiList []Tai `json:"taiList,omitempty"`

	PlmnList []PlmnId `json:"plmnList,omitempty"`
}

// AssertQmcAreaScopeRequired checks if the required fields are not zero-ed
func AssertQmcAreaScopeRequired(obj QmcAreaScope) error {
	for _, el := range obj.TaiList {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.PlmnList {
		if err := AssertPlmnIdRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertQmcAreaScopeConstraints checks if the values respects the defined constraints
func AssertQmcAreaScopeConstraints(obj QmcAreaScope) error {
	return nil
}
