/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// RangingSlPosSubscriptionData - Contains the Ranging/SL positioning Subscription Data.
type RangingSlPosSubscriptionData struct {

	RangingSlPosAuth RangingSlPosAuth `json:"rangingSlPosAuth,omitempty"`

	RangingSlPosPlmn []RangingSlPosPlmn `json:"rangingSlPosPlmn,omitempty"`

	RangingSlPosQos RangingSlPosQos `json:"rangingSlPosQos,omitempty"`
}

// AssertRangingSlPosSubscriptionDataRequired checks if the required fields are not zero-ed
func AssertRangingSlPosSubscriptionDataRequired(obj RangingSlPosSubscriptionData) error {
	if err := AssertRangingSlPosAuthRequired(obj.RangingSlPosAuth); err != nil {
		return err
	}
	for _, el := range obj.RangingSlPosPlmn {
		if err := AssertRangingSlPosPlmnRequired(el); err != nil {
			return err
		}
	}
	if err := AssertRangingSlPosQosRequired(obj.RangingSlPosQos); err != nil {
		return err
	}
	return nil
}

// AssertRangingSlPosSubscriptionDataConstraints checks if the values respects the defined constraints
func AssertRangingSlPosSubscriptionDataConstraints(obj RangingSlPosSubscriptionData) error {
	return nil
}
