/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// CodeWordInd - Indicates that the codeword shall be checked in UE or one or more codeword values to be checked in GMLC. 
type CodeWordInd struct {
}

// AssertCodeWordIndRequired checks if the required fields are not zero-ed
func AssertCodeWordIndRequired(obj CodeWordInd) error {
	return nil
}

// AssertCodeWordIndConstraints checks if the values respects the defined constraints
func AssertCodeWordIndConstraints(obj CodeWordInd) error {
	return nil
}
