/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// PduSessionContinuityInd - It indicates the handling of PDU session when the UE moves in and out of NB-IoT. In its absence, the local policy should be used. 
type PduSessionContinuityInd struct {
}

// AssertPduSessionContinuityIndRequired checks if the required fields are not zero-ed
func AssertPduSessionContinuityIndRequired(obj PduSessionContinuityInd) error {
	return nil
}

// AssertPduSessionContinuityIndConstraints checks if the values respects the defined constraints
func AssertPduSessionContinuityIndConstraints(obj PduSessionContinuityInd) error {
	return nil
}
