/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// UpLocRepIndAf - Indicates one of the mutually exclusive global settings for location reporting over user plane connectivity to an LCS client or AF. 
type UpLocRepIndAf struct {
}

// AssertUpLocRepIndAfRequired checks if the required fields are not zero-ed
func AssertUpLocRepIndAfRequired(obj UpLocRepIndAf) error {
	return nil
}

// AssertUpLocRepIndAfConstraints checks if the values respects the defined constraints
func AssertUpLocRepIndAfConstraints(obj UpLocRepIndAf) error {
	return nil
}
