/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ConditionalCagInfo struct {

	AllowedCagList []string `json:"allowedCagList"`

	CagOnlyIndicator bool `json:"cagOnlyIndicator,omitempty"`

	ValidTimePeriod ValidTimePeriod `json:"validTimePeriod,omitempty"`
}

// AssertConditionalCagInfoRequired checks if the required fields are not zero-ed
func AssertConditionalCagInfoRequired(obj ConditionalCagInfo) error {
	elements := map[string]interface{}{
		"allowedCagList": obj.AllowedCagList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertValidTimePeriodRequired(obj.ValidTimePeriod); err != nil {
		return err
	}
	return nil
}

// AssertConditionalCagInfoConstraints checks if the values respects the defined constraints
func AssertConditionalCagInfoConstraints(obj ConditionalCagInfo) error {
	return nil
}
