/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// MdtUserConsent - Indicates the user has given his consent for MDT activation. 
type MdtUserConsent struct {
}

// AssertMdtUserConsentRequired checks if the required fields are not zero-ed
func AssertMdtUserConsentRequired(obj MdtUserConsent) error {
	return nil
}

// AssertMdtUserConsentConstraints checks if the values respects the defined constraints
func AssertMdtUserConsentConstraints(obj MdtUserConsent) error {
	return nil
}
