/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ResponseTime - Indicates acceptable delay of location request.
type ResponseTime struct {
}

// AssertResponseTimeRequired checks if the required fields are not zero-ed
func AssertResponseTimeRequired(obj ResponseTime) error {
	return nil
}

// AssertResponseTimeConstraints checks if the values respects the defined constraints
func AssertResponseTimeConstraints(obj ResponseTime) error {
	return nil
}
