/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// LcsQosClass - Specifies LCS QoS class.
type LcsQosClass struct {
}

// AssertLcsQosClassRequired checks if the required fields are not zero-ed
func AssertLcsQosClassRequired(obj LcsQosClass) error {
	return nil
}

// AssertLcsQosClassConstraints checks if the values respects the defined constraints
func AssertLcsQosClassConstraints(obj LcsQosClass) error {
	return nil
}
