/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type A2xSubscriptionData struct {

	NrA2xServicesAuth NrA2xAuth `json:"nrA2xServicesAuth,omitempty"`

	LteA2xServicesAuth LteA2xAuth `json:"lteA2xServicesAuth,omitempty"`

	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	NrUePc5Ambr string `json:"nrUePc5Ambr,omitempty"`

	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	LtePc5Ambr string `json:"ltePc5Ambr,omitempty"`
}

// AssertA2xSubscriptionDataRequired checks if the required fields are not zero-ed
func AssertA2xSubscriptionDataRequired(obj A2xSubscriptionData) error {
	if err := AssertNrA2xAuthRequired(obj.NrA2xServicesAuth); err != nil {
		return err
	}
	if err := AssertLteA2xAuthRequired(obj.LteA2xServicesAuth); err != nil {
		return err
	}
	return nil
}

// AssertA2xSubscriptionDataConstraints checks if the values respects the defined constraints
func AssertA2xSubscriptionDataConstraints(obj A2xSubscriptionData) error {
	return nil
}
