/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// RangingSlPosAllowed - Indicates the Ranging/SL positioning services that can be authorised to  use in the given PLMN for the UE. 
type RangingSlPosAllowed struct {
}

// AssertRangingSlPosAllowedRequired checks if the required fields are not zero-ed
func AssertRangingSlPosAllowedRequired(obj RangingSlPosAllowed) error {
	return nil
}

// AssertRangingSlPosAllowedConstraints checks if the values respects the defined constraints
func AssertRangingSlPosAllowedConstraints(obj RangingSlPosAllowed) error {
	return nil
}
