/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"errors"
)



// ClockQuality - Contains Clock Quality.
type ClockQuality struct {

	TraceabilityToGnss bool `json:"traceabilityToGnss,omitempty"`

	TraceabilityToUtc bool `json:"traceabilityToUtc,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer. 
	FrequencyStability int32 `json:"frequencyStability,omitempty"`

	ClockAccuracy string `json:"clockAccuracy,omitempty"`
}

// AssertClockQualityRequired checks if the required fields are not zero-ed
func AssertClockQualityRequired(obj ClockQuality) error {
	return nil
}

// AssertClockQualityConstraints checks if the values respects the defined constraints
func AssertClockQualityConstraints(obj ClockQuality) error {
	if obj.FrequencyStability < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.FrequencyStability > 65535 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
