/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// QoeServiceType - The enumeration QoeServiceType indicates the kind of service that shall be recorded for QMC. It shall comply with the provisions defined in TS 29.571, table 5.6.3.21-1. 
type QoeServiceType struct {
}

// AssertQoeServiceTypeRequired checks if the required fields are not zero-ed
func AssertQoeServiceTypeRequired(obj QoeServiceType) error {
	return nil
}

// AssertQoeServiceTypeConstraints checks if the values respects the defined constraints
func AssertQoeServiceTypeConstraints(obj QoeServiceType) error {
	return nil
}
