/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ClockQualityAcceptanceCriterion - Contains a Clock Quality Acceptance Criterion.
type ClockQualityAcceptanceCriterion struct {

	SynchronizationState SynchronizationState `json:"synchronizationState,omitempty"`

	ClockQuality ClockQuality `json:"clockQuality,omitempty"`

	ParentTimeSource TimeSource `json:"parentTimeSource,omitempty"`
}

// AssertClockQualityAcceptanceCriterionRequired checks if the required fields are not zero-ed
func AssertClockQualityAcceptanceCriterionRequired(obj ClockQualityAcceptanceCriterion) error {
	if err := AssertSynchronizationStateRequired(obj.SynchronizationState); err != nil {
		return err
	}
	if err := AssertClockQualityRequired(obj.ClockQuality); err != nil {
		return err
	}
	if err := AssertTimeSourceRequired(obj.ParentTimeSource); err != nil {
		return err
	}
	return nil
}

// AssertClockQualityAcceptanceCriterionConstraints checks if the values respects the defined constraints
func AssertClockQualityAcceptanceCriterionConstraints(obj ClockQualityAcceptanceCriterion) error {
	return nil
}
