/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type LcsSubscriptionData struct {

	// LMF identification.
	ConfiguredLmfId string `json:"configuredLmfId,omitempty"`

	PruInd PruInd `json:"pruInd,omitempty"`

	LpHapType LpHapType `json:"lpHapType,omitempty"`

	UserPlanePosIndLmf bool `json:"userPlanePosIndLmf,omitempty"`
}

// AssertLcsSubscriptionDataRequired checks if the required fields are not zero-ed
func AssertLcsSubscriptionDataRequired(obj LcsSubscriptionData) error {
	if err := AssertPruIndRequired(obj.PruInd); err != nil {
		return err
	}
	if err := AssertLpHapTypeRequired(obj.LpHapType); err != nil {
		return err
	}
	return nil
}

// AssertLcsSubscriptionDataConstraints checks if the values respects the defined constraints
func AssertLcsSubscriptionDataConstraints(obj LcsSubscriptionData) error {
	return nil
}
