/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// DataSetName - Indicates the requested data set name.
type DataSetName struct {
}

// AssertDataSetNameRequired checks if the required fields are not zero-ed
func AssertDataSetNameRequired(obj DataSetName) error {
	return nil
}

// AssertDataSetNameConstraints checks if the values respects the defined constraints
func AssertDataSetNameConstraints(obj DataSetName) error {
	return nil
}
