/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AvailableRanVisibleQoeMetric - The enumeration AvailableRanVisibleQoeMetric indicates different available RAN-visible QoE metrics to the gNB. It shall comply with the provisions defined in TS 29.571, table 5.6.3.22-1. 
type AvailableRanVisibleQoeMetric struct {
}

// AssertAvailableRanVisibleQoeMetricRequired checks if the required fields are not zero-ed
func AssertAvailableRanVisibleQoeMetricRequired(obj AvailableRanVisibleQoeMetric) error {
	return nil
}

// AssertAvailableRanVisibleQoeMetricConstraints checks if the values respects the defined constraints
func AssertAvailableRanVisibleQoeMetricConstraints(obj AvailableRanVisibleQoeMetric) error {
	return nil
}
