/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ClockQualityDetailLevel - Indicates the Clock Quality Detail Level.
type ClockQualityDetailLevel struct {
}

// AssertClockQualityDetailLevelRequired checks if the required fields are not zero-ed
func AssertClockQualityDetailLevelRequired(obj ClockQualityDetailLevel) error {
	return nil
}

// AssertClockQualityDetailLevelConstraints checks if the values respects the defined constraints
func AssertClockQualityDetailLevelConstraints(obj ClockQualityDetailLevel) error {
	return nil
}
