/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

type AppSpecificExpectedUeBehaviourData struct {

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	TrafficFilters []FlowInfo `json:"trafficFilters,omitempty"`

	// indicating a time in seconds.
	ExpectedInactivityTime int32 `json:"expectedInactivityTime,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	ConfidenceLevel string `json:"confidenceLevel,omitempty"`

	AccuracyLevel string `json:"accuracyLevel,omitempty"`
}

// AssertAppSpecificExpectedUeBehaviourDataRequired checks if the required fields are not zero-ed
func AssertAppSpecificExpectedUeBehaviourDataRequired(obj AppSpecificExpectedUeBehaviourData) error {
	for _, el := range obj.TrafficFilters {
		if err := AssertFlowInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAppSpecificExpectedUeBehaviourDataConstraints checks if the values respects the defined constraints
func AssertAppSpecificExpectedUeBehaviourDataConstraints(obj AppSpecificExpectedUeBehaviourData) error {
	return nil
}
