/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// PruInd - Indicates whether the UE can act as a PRU or the type of PRU. 
type PruInd struct {
}

// AssertPruIndRequired checks if the required fields are not zero-ed
func AssertPruIndRequired(obj PruInd) error {
	return nil
}

// AssertPruIndConstraints checks if the values respects the defined constraints
func AssertPruIndConstraints(obj PruInd) error {
	return nil
}
