/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// FlowInfo - Represents IP flow information.
type FlowInfo struct {

	// Indicates the IP flow identifier.
	FlowId int32 `json:"flowId"`

	// Indicates the packet filters of the IP flow. Refer to clause 5.3.8 of 3GPP TS 29.214 for encoding. It shall contain UL and/or DL IP flow description. 
	FlowDescriptions []string `json:"flowDescriptions,omitempty"`

	// 2-octet string, where each octet is encoded in hexadecimal representation. The first octet contains the IPv4 Type-of-Service or the IPv6 Traffic-Class field and the second octet contains the ToS/Traffic Class mask field. 
	TosTC string `json:"tosTC,omitempty"`
}

// AssertFlowInfoRequired checks if the required fields are not zero-ed
func AssertFlowInfoRequired(obj FlowInfo) error {
	elements := map[string]interface{}{
		"flowId": obj.FlowId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertFlowInfoConstraints checks if the values respects the defined constraints
func AssertFlowInfoConstraints(obj FlowInfo) error {
	return nil
}
