/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// MbsServiceType - Indicates the MBS service type of an MBS session
type MbsServiceType struct {
}

// AssertMbsServiceTypeRequired checks if the required fields are not zero-ed
func AssertMbsServiceTypeRequired(obj MbsServiceType) error {
	return nil
}

// AssertMbsServiceTypeConstraints checks if the values respects the defined constraints
func AssertMbsServiceTypeConstraints(obj MbsServiceType) error {
	return nil
}
