/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// WirelineArea - One and only one of the \"globLineIds\", \"hfcNIds\", \"areaCodeB\",d \"areaCodeC\" and  combGciAndHfcNIds attributes        shall be included in a WirelineArea data structure 
type WirelineArea struct {

	GlobalLineIds []string `json:"globalLineIds,omitempty"`

	HfcNIds []string `json:"hfcNIds,omitempty"`

	// Values are operator specific.
	AreaCodeB string `json:"areaCodeB,omitempty"`

	// Values are operator specific.
	AreaCodeC string `json:"areaCodeC,omitempty"`

	CombGciAndHfcNIds []CombGciAndHfcNIds `json:"combGciAndHfcNIds,omitempty"`
}

// AssertWirelineAreaRequired checks if the required fields are not zero-ed
func AssertWirelineAreaRequired(obj WirelineArea) error {
	for _, el := range obj.CombGciAndHfcNIds {
		if err := AssertCombGciAndHfcNIdsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertWirelineAreaConstraints checks if the values respects the defined constraints
func AssertWirelineAreaConstraints(obj WirelineArea) error {
	return nil
}
