/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// TimeSource - Indicates the Time Source.
type TimeSource struct {
}

// AssertTimeSourceRequired checks if the required fields are not zero-ed
func AssertTimeSourceRequired(obj TimeSource) error {
	return nil
}

// AssertTimeSourceConstraints checks if the values respects the defined constraints
func AssertTimeSourceConstraints(obj TimeSource) error {
	return nil
}
