/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type MbsrOperationAllowed struct {

	MbsrOperationAllowedInd bool `json:"mbsrOperationAllowedInd,omitempty"`

	MbsrValidTimePeriod ValidTimePeriod `json:"mbsrValidTimePeriod,omitempty"`
}

// AssertMbsrOperationAllowedRequired checks if the required fields are not zero-ed
func AssertMbsrOperationAllowedRequired(obj MbsrOperationAllowed) error {
	if err := AssertValidTimePeriodRequired(obj.MbsrValidTimePeriod); err != nil {
		return err
	}
	return nil
}

// AssertMbsrOperationAllowedConstraints checks if the values respects the defined constraints
func AssertMbsrOperationAllowedConstraints(obj MbsrOperationAllowed) error {
	return nil
}
