/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// OperationMode - Indicates the Operation Mode. 
type OperationMode struct {
}

// AssertOperationModeRequired checks if the required fields are not zero-ed
func AssertOperationModeRequired(obj OperationMode) error {
	return nil
}

// AssertOperationModeConstraints checks if the values respects the defined constraints
func AssertOperationModeConstraints(obj OperationMode) error {
	return nil
}
