/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// NsacAdmissionMode - Indicates the NSAC admission mode applied in roaming case. 
type NsacAdmissionMode struct {
}

// AssertNsacAdmissionModeRequired checks if the required fields are not zero-ed
func AssertNsacAdmissionModeRequired(obj NsacAdmissionMode) error {
	return nil
}

// AssertNsacAdmissionModeConstraints checks if the values respects the defined constraints
func AssertNsacAdmissionModeConstraints(obj NsacAdmissionMode) error {
	return nil
}
