/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// LcsMoServiceClass - Indicates the requirement of the UE to request its own location. 
type LcsMoServiceClass struct {
}

// AssertLcsMoServiceClassRequired checks if the required fields are not zero-ed
func AssertLcsMoServiceClassRequired(obj LcsMoServiceClass) error {
	return nil
}

// AssertLcsMoServiceClassConstraints checks if the values respects the defined constraints
func AssertLcsMoServiceClassConstraints(obj LcsMoServiceClass) error {
	return nil
}
