/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"errors"
)



// AstiAllowedInfo - AF authorization information for ASTI
type AstiAllowedInfo struct {

	AstiAllowed bool `json:"astiAllowed"`

	CoverageArea []Tai `json:"coverageArea,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UuTimeSyncErrBdgt int32 `json:"uuTimeSyncErrBdgt,omitempty"`

	TempVals []TemporalValidity `json:"tempVals,omitempty"`
}

// AssertAstiAllowedInfoRequired checks if the required fields are not zero-ed
func AssertAstiAllowedInfoRequired(obj AstiAllowedInfo) error {
	elements := map[string]interface{}{
		"astiAllowed": obj.AstiAllowed,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.CoverageArea {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.TempVals {
		if err := AssertTemporalValidityRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAstiAllowedInfoConstraints checks if the values respects the defined constraints
func AssertAstiAllowedInfoConstraints(obj AstiAllowedInfo) error {
	if obj.UuTimeSyncErrBdgt < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
