/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// NrA2xAuth - Contains NR A2X services authorized information.
type NrA2xAuth struct {

	UavUeAuth UeAuth `json:"uavUeAuth,omitempty"`
}

// AssertNrA2xAuthRequired checks if the required fields are not zero-ed
func AssertNrA2xAuthRequired(obj NrA2xAuth) error {
	if err := AssertUeAuthRequired(obj.UavUeAuth); err != nil {
		return err
	}
	return nil
}

// AssertNrA2xAuthConstraints checks if the values respects the defined constraints
func AssertNrA2xAuthConstraints(obj NrA2xAuth) error {
	return nil
}
