/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// LpHapType - Type of Low Power and/or High Accuracy Positioning
type LpHapType struct {
}

// AssertLpHapTypeRequired checks if the required fields are not zero-ed
func AssertLpHapTypeRequired(obj LpHapType) error {
	return nil
}

// AssertLpHapTypeConstraints checks if the values respects the defined constraints
func AssertLpHapTypeConstraints(obj LpHapType) error {
	return nil
}
