/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type DnnLadnServiceAreas struct {

	DnnLadnServiceAreas []DnnLadnServiceArea `json:"dnnLadnServiceAreas"`
}

// AssertDnnLadnServiceAreasRequired checks if the required fields are not zero-ed
func AssertDnnLadnServiceAreasRequired(obj DnnLadnServiceAreas) error {
	elements := map[string]interface{}{
		"dnnLadnServiceAreas": obj.DnnLadnServiceAreas,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DnnLadnServiceAreas {
		if err := AssertDnnLadnServiceAreaRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDnnLadnServiceAreasConstraints checks if the values respects the defined constraints
func AssertDnnLadnServiceAreasConstraints(obj DnnLadnServiceAreas) error {
	return nil
}
