/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"errors"
)



type TimeSyncData struct {

	Authorized bool `json:"authorized"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UuTimeSyncErrBdgt int32 `json:"uuTimeSyncErrBdgt,omitempty"`

	TempVals []TemporalValidity `json:"tempVals,omitempty"`

	CoverageArea []Tai `json:"coverageArea,omitempty"`

	ClockQualityDetailLevel ClockQualityDetailLevel `json:"clockQualityDetailLevel,omitempty"`

	ClockQualityAcceptanceCriteria []ClockQualityAcceptanceCriterion `json:"clockQualityAcceptanceCriteria,omitempty"`
}

// AssertTimeSyncDataRequired checks if the required fields are not zero-ed
func AssertTimeSyncDataRequired(obj TimeSyncData) error {
	elements := map[string]interface{}{
		"authorized": obj.Authorized,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.TempVals {
		if err := AssertTemporalValidityRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.CoverageArea {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	if err := AssertClockQualityDetailLevelRequired(obj.ClockQualityDetailLevel); err != nil {
		return err
	}
	for _, el := range obj.ClockQualityAcceptanceCriteria {
		if err := AssertClockQualityAcceptanceCriterionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTimeSyncDataConstraints checks if the values respects the defined constraints
func AssertTimeSyncDataConstraints(obj TimeSyncData) error {
	if obj.UuTimeSyncErrBdgt < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
