/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// SynchronizationState - Indicates the Synchronization State.
type SynchronizationState struct {
}

// AssertSynchronizationStateRequired checks if the required fields are not zero-ed
func AssertSynchronizationStateRequired(obj SynchronizationState) error {
	return nil
}

// AssertSynchronizationStateConstraints checks if the values respects the defined constraints
func AssertSynchronizationStateConstraints(obj SynchronizationState) error {
	return nil
}
