/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	"github.com/go-redis/redis/v8"
)

func main() {
	log.Printf("Server started")

	// Connect to Redis.
	rdb := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "", // no password set
		DB:       0,  // use the default database
	})

	// Ping the Redis server to check if it's reachable.
	pong, err := rdb.Ping(context.Background()).Result()
	if err != nil {
		fmt.Println("Error connecting to Redis:", err)
		return
	}
	fmt.Println("Connected to Redis:", pong)

	// // Iterate over the map and store each entry in Redis.
	// for key, value := range subscriptions {
	// 	// Convert the value to JSON (or any suitable format) to store in Redis.
	// 	// For simplicity, let's assume SessionManagementSubscriptionData is a struct.
	// 	data, err := json.Marshal(value)
	// 	if err != nil {
	// 		fmt.Println(err)
	// 	}

	// 	// Store the data in Redis using the key.
	// 	err = rdb.Set(context.Background(), key, data, 0).Err()
	// 	if err != nil {
	// 		fmt.Println(err)
	// 	}
	// }

	A2XSubscriptionDataRetrievalAPIService := openapi.NewA2XSubscriptionDataRetrievalAPIService()
	A2XSubscriptionDataRetrievalAPIController := openapi.NewA2XSubscriptionDataRetrievalAPIController(A2XSubscriptionDataRetrievalAPIService)

	AccessAndMobilitySubscriptionDataRetrievalAPIService := openapi.NewAccessAndMobilitySubscriptionDataRetrievalAPIService()
	AccessAndMobilitySubscriptionDataRetrievalAPIController := openapi.NewAccessAndMobilitySubscriptionDataRetrievalAPIController(AccessAndMobilitySubscriptionDataRetrievalAPIService)

	Class5MBSSubscriptionDataRetrievalAPIService := openapi.NewClass5MBSSubscriptionDataRetrievalAPIService()
	Class5MBSSubscriptionDataRetrievalAPIController := openapi.NewClass5MBSSubscriptionDataRetrievalAPIController(Class5MBSSubscriptionDataRetrievalAPIService)

	EnhancedCoverageRestrictionDataRetrievalAPIService := openapi.NewEnhancedCoverageRestrictionDataRetrievalAPIService()
	EnhancedCoverageRestrictionDataRetrievalAPIController := openapi.NewEnhancedCoverageRestrictionDataRetrievalAPIController(EnhancedCoverageRestrictionDataRetrievalAPIService)

	GPSIToSUPITranslationOrSUPIToGPSITranslationAPIService := openapi.NewGPSIToSUPITranslationOrSUPIToGPSITranslationAPIService()
	GPSIToSUPITranslationOrSUPIToGPSITranslationAPIController := openapi.NewGPSIToSUPITranslationOrSUPIToGPSITranslationAPIController(GPSIToSUPITranslationOrSUPIToGPSITranslationAPIService)

	GroupIdentifiersAPIService := openapi.NewGroupIdentifiersAPIService()
	GroupIdentifiersAPIController := openapi.NewGroupIdentifiersAPIController(GroupIdentifiersAPIService)

	LCSBroadcastAssistanceDataTypesRetrievalAPIService := openapi.NewLCSBroadcastAssistanceDataTypesRetrievalAPIService()
	LCSBroadcastAssistanceDataTypesRetrievalAPIController := openapi.NewLCSBroadcastAssistanceDataTypesRetrievalAPIController(LCSBroadcastAssistanceDataTypesRetrievalAPIService)

	LCSMobileOriginatedDataRetrievalAPIService := openapi.NewLCSMobileOriginatedDataRetrievalAPIService()
	LCSMobileOriginatedDataRetrievalAPIController := openapi.NewLCSMobileOriginatedDataRetrievalAPIController(LCSMobileOriginatedDataRetrievalAPIService)

	LCSPrivacyDataRetrievalAPIService := openapi.NewLCSPrivacyDataRetrievalAPIService()
	LCSPrivacyDataRetrievalAPIController := openapi.NewLCSPrivacyDataRetrievalAPIController(LCSPrivacyDataRetrievalAPIService)

	LCSSubscriptionDataRetrievalAPIService := openapi.NewLCSSubscriptionDataRetrievalAPIService()
	LCSSubscriptionDataRetrievalAPIController := openapi.NewLCSSubscriptionDataRetrievalAPIController(LCSSubscriptionDataRetrievalAPIService)

	MultipleIdentifiersAPIService := openapi.NewMultipleIdentifiersAPIService()
	MultipleIdentifiersAPIController := openapi.NewMultipleIdentifiersAPIController(MultipleIdentifiersAPIService)

	ProseSubscriptionDataRetrievalAPIService := openapi.NewProseSubscriptionDataRetrievalAPIService()
	ProseSubscriptionDataRetrievalAPIController := openapi.NewProseSubscriptionDataRetrievalAPIController(ProseSubscriptionDataRetrievalAPIService)

	ProvidingAcknowledgementOfCAGUpdateAPIService := openapi.NewProvidingAcknowledgementOfCAGUpdateAPIService()
	ProvidingAcknowledgementOfCAGUpdateAPIController := openapi.NewProvidingAcknowledgementOfCAGUpdateAPIController(ProvidingAcknowledgementOfCAGUpdateAPIService)

	ProvidingAcknowledgementOfSNSSAIsUpdateAPIService := openapi.NewProvidingAcknowledgementOfSNSSAIsUpdateAPIService()
	ProvidingAcknowledgementOfSNSSAIsUpdateAPIController := openapi.NewProvidingAcknowledgementOfSNSSAIsUpdateAPIController(ProvidingAcknowledgementOfSNSSAIsUpdateAPIService)

	ProvidingAcknowledgementOfSteeringOfRoamingAPIService := openapi.NewProvidingAcknowledgementOfSteeringOfRoamingAPIService()
	ProvidingAcknowledgementOfSteeringOfRoamingAPIController := openapi.NewProvidingAcknowledgementOfSteeringOfRoamingAPIController(ProvidingAcknowledgementOfSteeringOfRoamingAPIService)

	ProvidingAcknowledgementOfUEParametersUpdateAPIService := openapi.NewProvidingAcknowledgementOfUEParametersUpdateAPIService()
	ProvidingAcknowledgementOfUEParametersUpdateAPIController := openapi.NewProvidingAcknowledgementOfUEParametersUpdateAPIController(ProvidingAcknowledgementOfUEParametersUpdateAPIService)

	RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIService := openapi.NewRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIService()
	RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController := openapi.NewRangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController(RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIService)

	RetrievalOfMultipleDataSetsAPIService := openapi.NewRetrievalOfMultipleDataSetsAPIService()
	RetrievalOfMultipleDataSetsAPIController := openapi.NewRetrievalOfMultipleDataSetsAPIController(RetrievalOfMultipleDataSetsAPIService)

	RetrievalOfSharedDataAPIService := openapi.NewRetrievalOfSharedDataAPIService()
	RetrievalOfSharedDataAPIController := openapi.NewRetrievalOfSharedDataAPIController(RetrievalOfSharedDataAPIService)

	RetrievalOfTheIndividualSharedDataAPIService := openapi.NewRetrievalOfTheIndividualSharedDataAPIService()
	RetrievalOfTheIndividualSharedDataAPIController := openapi.NewRetrievalOfTheIndividualSharedDataAPIController(RetrievalOfTheIndividualSharedDataAPIService)

	SMFSelectionSubscriptionDataRetrievalAPIService := openapi.NewSMFSelectionSubscriptionDataRetrievalAPIService()
	SMFSelectionSubscriptionDataRetrievalAPIController := openapi.NewSMFSelectionSubscriptionDataRetrievalAPIController(SMFSelectionSubscriptionDataRetrievalAPIService)

	SMSManagementSubscriptionDataRetrievalAPIService := openapi.NewSMSManagementSubscriptionDataRetrievalAPIService()
	SMSManagementSubscriptionDataRetrievalAPIController := openapi.NewSMSManagementSubscriptionDataRetrievalAPIController(SMSManagementSubscriptionDataRetrievalAPIService)

	SMSSubscriptionDataRetrievalAPIService := openapi.NewSMSSubscriptionDataRetrievalAPIService()
	SMSSubscriptionDataRetrievalAPIController := openapi.NewSMSSubscriptionDataRetrievalAPIController(SMSSubscriptionDataRetrievalAPIService)

	SessionManagementSubscriptionDataRetrievalAPIService := openapi.NewSessionManagementSubscriptionDataRetrievalAPIService(rdb, context.Background())
	SessionManagementSubscriptionDataRetrievalAPIController := openapi.NewSessionManagementSubscriptionDataRetrievalAPIController(SessionManagementSubscriptionDataRetrievalAPIService)

	SliceSelectionSubscriptionDataRetrievalAPIService := openapi.NewSliceSelectionSubscriptionDataRetrievalAPIService()
	SliceSelectionSubscriptionDataRetrievalAPIController := openapi.NewSliceSelectionSubscriptionDataRetrievalAPIController(SliceSelectionSubscriptionDataRetrievalAPIService)

	SubscriptionCreationAPIService := openapi.NewSubscriptionCreationAPIService()
	SubscriptionCreationAPIController := openapi.NewSubscriptionCreationAPIController(SubscriptionCreationAPIService)

	SubscriptionCreationForSharedDataAPIService := openapi.NewSubscriptionCreationForSharedDataAPIService()
	SubscriptionCreationForSharedDataAPIController := openapi.NewSubscriptionCreationForSharedDataAPIController(SubscriptionCreationForSharedDataAPIService)

	SubscriptionDeletionAPIService := openapi.NewSubscriptionDeletionAPIService()
	SubscriptionDeletionAPIController := openapi.NewSubscriptionDeletionAPIController(SubscriptionDeletionAPIService)

	SubscriptionDeletionForSharedDataAPIService := openapi.NewSubscriptionDeletionForSharedDataAPIService()
	SubscriptionDeletionForSharedDataAPIController := openapi.NewSubscriptionDeletionForSharedDataAPIController(SubscriptionDeletionForSharedDataAPIService)

	SubscriptionModificationAPIService := openapi.NewSubscriptionModificationAPIService()
	SubscriptionModificationAPIController := openapi.NewSubscriptionModificationAPIController(SubscriptionModificationAPIService)

	TimeSyncSubscriptionDataRetrievalAPIService := openapi.NewTimeSyncSubscriptionDataRetrievalAPIService()
	TimeSyncSubscriptionDataRetrievalAPIController := openapi.NewTimeSyncSubscriptionDataRetrievalAPIController(TimeSyncSubscriptionDataRetrievalAPIService)

	TraceConfigurationDataRetrievalAPIService := openapi.NewTraceConfigurationDataRetrievalAPIService()
	TraceConfigurationDataRetrievalAPIController := openapi.NewTraceConfigurationDataRetrievalAPIController(TraceConfigurationDataRetrievalAPIService)

	TriggerSORInfoUpdateAPIService := openapi.NewTriggerSORInfoUpdateAPIService()
	TriggerSORInfoUpdateAPIController := openapi.NewTriggerSORInfoUpdateAPIController(TriggerSORInfoUpdateAPIService)

	UEContextInAMFDataRetrievalAPIService := openapi.NewUEContextInAMFDataRetrievalAPIService()
	UEContextInAMFDataRetrievalAPIController := openapi.NewUEContextInAMFDataRetrievalAPIController(UEContextInAMFDataRetrievalAPIService)

	UEContextInSMFDataRetrievalAPIService := openapi.NewUEContextInSMFDataRetrievalAPIService()
	UEContextInSMFDataRetrievalAPIController := openapi.NewUEContextInSMFDataRetrievalAPIController(UEContextInSMFDataRetrievalAPIService)

	UEContextInSMSFDataRetrievalAPIService := openapi.NewUEContextInSMSFDataRetrievalAPIService()
	UEContextInSMSFDataRetrievalAPIController := openapi.NewUEContextInSMSFDataRetrievalAPIController(UEContextInSMSFDataRetrievalAPIService)

	UserConsentSubscriptionDataRetrievalAPIService := openapi.NewUserConsentSubscriptionDataRetrievalAPIService()
	UserConsentSubscriptionDataRetrievalAPIController := openapi.NewUserConsentSubscriptionDataRetrievalAPIController(UserConsentSubscriptionDataRetrievalAPIService)

	V2XSubscriptionDataRetrievalAPIService := openapi.NewV2XSubscriptionDataRetrievalAPIService()
	V2XSubscriptionDataRetrievalAPIController := openapi.NewV2XSubscriptionDataRetrievalAPIController(V2XSubscriptionDataRetrievalAPIService)

	router := openapi.NewRouter(A2XSubscriptionDataRetrievalAPIController, AccessAndMobilitySubscriptionDataRetrievalAPIController, Class5MBSSubscriptionDataRetrievalAPIController, EnhancedCoverageRestrictionDataRetrievalAPIController, GPSIToSUPITranslationOrSUPIToGPSITranslationAPIController, GroupIdentifiersAPIController, LCSBroadcastAssistanceDataTypesRetrievalAPIController, LCSMobileOriginatedDataRetrievalAPIController, LCSPrivacyDataRetrievalAPIController, LCSSubscriptionDataRetrievalAPIController, MultipleIdentifiersAPIController, ProseSubscriptionDataRetrievalAPIController, ProvidingAcknowledgementOfCAGUpdateAPIController, ProvidingAcknowledgementOfSNSSAIsUpdateAPIController, ProvidingAcknowledgementOfSteeringOfRoamingAPIController, ProvidingAcknowledgementOfUEParametersUpdateAPIController, RangingAndSidelinkPositioningSubscriptionDataRetrievalAPIController, RetrievalOfMultipleDataSetsAPIController, RetrievalOfSharedDataAPIController, RetrievalOfTheIndividualSharedDataAPIController, SMFSelectionSubscriptionDataRetrievalAPIController, SMSManagementSubscriptionDataRetrievalAPIController, SMSSubscriptionDataRetrievalAPIController, SessionManagementSubscriptionDataRetrievalAPIController, SliceSelectionSubscriptionDataRetrievalAPIController, SubscriptionCreationAPIController, SubscriptionCreationForSharedDataAPIController, SubscriptionDeletionAPIController, SubscriptionDeletionForSharedDataAPIController, SubscriptionModificationAPIController, TimeSyncSubscriptionDataRetrievalAPIController, TraceConfigurationDataRetrievalAPIController, TriggerSORInfoUpdateAPIController, UEContextInAMFDataRetrievalAPIController, UEContextInSMFDataRetrievalAPIController, UEContextInSMSFDataRetrievalAPIController, UserConsentSubscriptionDataRetrievalAPIController, V2XSubscriptionDataRetrievalAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
